#ifndef STATE_H
#define STATE_H

enum SystemState {
    STATE_MAIN,
    STATE_MENU_ROOT,
    STATE_MENU_DEVICE,
    STATE_MENU_MSRMT,
    STATE_MENU_SYSTEM,
    STATE_EDIT_CONTRAST,
    STATE_EDIT_BRIGHTNESS,
    STATE_EDIT_AUTO_OFF_TIMEOUT,
    STATE_EDIT_BATTERY_CAPACITY,
    STATE_EDIT_COUNT_UNIT,
    STATE_EDIT_DOSE_UNIT
};

#endif